@echo off
echo Starting Frontend...
cd frontend
echo Installing dependencies if missing...
call "C:\Program Files\nodejs\npm.cmd" install
echo Starting Vite Server...
call "C:\Program Files\nodejs\npm.cmd" run dev
pause
